version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: metas_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: metas_mysql
      MYSQL_USER: metas_user
      MYSQL_PASSWORD: metas_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - metas_network

  postgres:
    image: postgres:15
    container_name: metas_postgres
    restart: always
    environment:
      POSTGRES_DB: metas_postgres
      POSTGRES_USER: metas_user
      POSTGRES_PASSWORD: metas_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - metas_network

  adminer:
    image: adminer
    container_name: metas_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - metas_network
    depends_on:
      - mysql
      - postgres

volumes:
  mysql_data:
  postgres_data:

networks:
  metas_network:
    driver: bridge